version: '3.7'
services:
  corganized-copier:
    container_name: corganized-copier
    build: .
    command: /bin/bash entrypoint.sh
    restart: unless-stopped
    environment:
      TZ: America/Denver
      CONFIG_OVERRIDE_PATH: /shared/config.yml
    volumes:
      - ./mnt:/shared
      - ./mnt:/backup
