version: '3.7'
services:
  corganized-copier:
    container_name: corganized-copier
    build: .
    command: /bin/bash entrypoint.sh
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      CRG_SERVER_HOST: ${CRG_SERVER_HOST}
      CRG_SERVER_APIKEY: ${CRG_SERVER_APIKEY}
    volumes:
      - ${CONFIG_MNT_PATH}:/shared
      - ${BACKUP_DIR}:/backup
